name: 'Go Git Commit Action'
description: 'Automatically commit and push changes using Go'
author: 'somaz'

inputs:
  user_email:
    description: 'Git user email'
    required: true
  user_name:
    description: 'Git user name'
    required: true
  commit_message:
    description: 'Commit message'
    required: true
    default: 'Auto commit by Go Git Commit Action'
  branch:
    description: 'Branch to push to'
    required: true
    default: 'main'
  repository_path:
    description: 'Path to the repository'
    required: false
    default: '.'
  file_pattern:
    description: 'File pattern to add'
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    USER_EMAIL: ${{ inputs.user_email }}
    USER_NAME: ${{ inputs.user_name }}
    COMMIT_MESSAGE: ${{ inputs.commit_message }}
    BRANCH: ${{ inputs.branch }}
    REPOSITORY_PATH: ${{ inputs.repository_path }}
    FILE_PATTERN: ${{ inputs.file_pattern }}

branding:
  icon: 'git-commit'
  color: 'blue'
